version: "3.4"

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./databases/mongo:/data/db
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - 8081:8081
    environment:
      - REDIS_HOSTS=redis
    depends_on:
      - redis